import InfoCard from '@/components/common/info-card';
import routes from '@/config/routes';

const Page = () => {
  return (
    <main className="container mx-auto  items-center flex flex-col  gap-14 px-8 py-6 md:px-16 md:py-12  max-w-[1440px] h-full">
      <div
        className={
          ' mx-auto grid grid-cols-1 sm:grid-cols-2 max-w-6xl lg:grid-cols-3 gap-x-6 gap-y-6'
        }
      >
        {tools.map((tool, index) => (
          <InfoCard key={index} {...tool} />
        ))}
      </div>
    </main>
  );
};

export default Page;

const tools: {
  image: string;
  name: string;
  description: string;
  href?: string;
  disabled?: boolean;
}[] = [
  {
    image: '/icons/earn/dynamic-vault.png',
    name: 'Dynamic Vaults',
    description:
      'Optimize possible yields between top lending protocols with dynamically rebalancing vaults.',
    href: routes.earn.dynamicVault,
  },
  {
    name: 'NFT Farms',
    description:
      'Stake tokens to receive points which can be utilized to redeem vaulted NFTs.',
    image: '/icons/earn/nft-farms.svg',
    href: routes.earn.root,
  },
  {
    name: 'Liquid Staking',
    description:
      'Stake your Solana and earn while being able to swap & participate in DeFi.',
    image: '/icons/earn/liquidity-staking.svg',
    href: routes.earn.root,
  },
  {
    image: '/icons/earn/liquidity-farming.svg',
    name: 'GUAC Staking',
    description:
      'Stake your GUAC tokens to participate in governance and earn fees generated by the Guacamole protocol and ecosystem.',
    href: routes.earn.guacStaking,
  },
  {
    name: 'Liquidity Farming',
    description:
      'Power up your liquidity provision to earn extra liquidity mining rewards.',
    image: '/icons/earn/liquidity-farming.svg',
    href: routes.tools.root,
    disabled: true,
  },
  {
    image: '/icons/earn/liquidity-farming.svg',
    name: '(Comming Soon)',
    description:
      'We like to keep some things a secret. Come back soon as we perfect these ingredients.',
    href: '',
    disabled: true,
  },
];
