import InfoCard from '@/components/common/info-card';
import routes from '@/config/routes';
import { Metadata } from 'next';
import { FC } from 'react';

export const metadata: Metadata = {
  title: 'Useful Tools For All Solana Users | Guacamole',
  description:
    'Find a variety of easy to use tools in our suite that can instantly help improve your quality of life while interacting with the Solana blockchain or starting your own project!',
};
const Earn: FC = () => {
  return (
    <main className="container mx-auto  items-center flex flex-col  gap-14 px-8 py-6 md:px-16 md:py-12  max-w-[1440px]">
      <div
        className={
          ' mx-auto grid grid-cols-1 sm:grid-cols-2 max-w-6xl lg:grid-cols-3 gap-x-6 gap-y-6'
        }
      >
        {tools.map((tool, index) => (
          <InfoCard key={index} {...tool} />
        ))}
      </div>
    </main>
  );
};

export default Earn;

const tools: {
  image: string;
  name: string;
  description: string;
  href?: string;
  disabled?: boolean;
}[] = [
  {
    image: '/images/earn/dynamic-vault.png',
    name: 'Dynamic Vaults',
    description:
      'Optimize possible yields between top lending protocols with dynamically rebalancing vaults.',
    href: routes.earn.dynamicVault,
    disabled: true,

  },
  {
    image: '/images/earn/nft-pool.png',
    name: 'Token For NFT STAKING',
    description:
      'Stake tokens to receive points which can be utilized to redeem vaulted NFTs. Any project can start a staking pool!',
    href: routes.earn.statistics,
    disabled: true,

  },
  {
    image: '/images/earn/token-pool.png',
    name: 'NFT STAKING POOLS',
    description:
      'Stake your NFTs to receive points or tokens. Any project can start a staking pool in just a few simple clicks!',
    href: '',
    disabled: true,
  },
  {
    image: '/images/earn/guac.png',
    name: 'GUAC STAKING',
    description:
      'Stake your GUAC tokens to participate in governance and earn fees generated by the Guacamole protocol and ecosystem.',
    href: '',
    disabled: true,
  },
  {
    image: '/images/earn/liquidity-farming.png',
    name: 'LIQUIDITY FARMING',
    description:
      'Looking to put your LP tokens to work?Power up your liquidity provision to earn extra liquidity mining rewards.',
    href: '',
    disabled: true,
  },
  {
    image: '/images/earn/features.png',
    name: 'UNANNOUNCED FEATURE',
    description:
      'Guacamole likes to keep some things a secret. Come back soon as we perfect these ingredients.',
    href: '',
    disabled: true,
  },
];
